services:
  gateway:
    build:
      context: ./backend/gateway
    ports:
      - "3000:3000"
    depends_on:
      - admin-service
      - delivery-service
      - notification-service
      - payment-service
      - restaurant-service
      - user-service

  admin-service:
    build:
      context: ./backend/admin_service
    ports:
      - "5100:5100"

  delivery-service:
    build:
      context: ./backend/delivery_service
    ports:
      - "5200:5200"

  notification-service:
    build:
      context: ./backend/notification_service
    ports:
      - "5300:5300"

  payment-service:
    build:
      context: ./backend/payment_service
    ports:
      - "5400:5400"

  restaurant-service:
    build:
      context: ./backend/resturent_service
    ports:
      - "5500:5500"

  user-service:
    build:
      context: ./backend/user_service
    ports:
      - "5600:5600"