apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: foodiego-backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: ashokankuganathan/foodiego-payment-service:latest
        ports:
        - containerPort: 5400
        envFrom:
        - configMapRef:
            name: payment-service-config