apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: foodiego-backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: ashokankuganathan/foodiego-notification-service:latest
        ports:
        - containerPort: 5300
        envFrom:
        - configMapRef:
            name: notification-service-config